####### App Info #########
name: clean_arc
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.0
####### Dependencies #########
dependencies:
  flutter:
    sdk: flutter
  # start Core
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^6.0.0
  skeletonizer: ^2.1.0+1

  flutter_screenutil: ^5.9.0

  flutter_easyloading: ^3.0.5

  gif: ^2.3.0

  # Equality
  equatable: ^2.0.5
  timeago:
  webview_flutter:
  flutter_svg: ^2.0.10+1
  #  auto_route: ^7.9.0
  #  go_router: ^13.2.0
  overlay_support: ^2.1.0
  internet_connection_checker: ^1.0.0
#  flutter_localization: ^0.3.3
  loading_animation_widget: ^1.2.0+4
  top_snackbar_flutter: ^3.1.0
#  intl: ^0.19.0
  #sign-qr
  hand_signature: ^3.0.3
  flutter_barcode_listener: ^0.1.4
  # face_camera: ^0.1.4
  flutter_iconly: ^1.0.2
  flutter_dash: ^1.0.0
  #  awesome_notifications: ^0.10.1
  #  device_preview: ^1.1.0
  #  FireBase

  get_it: ^8.2.0
  injectable: ^2.4.0
  calendar_date_picker2: ^2.0.1
  #Api
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.4.2
  pretty_dio_logger: ^1.4.0
  logger: ^2.2.0
  retrofit: ^4.1.0
  dartz: ^0.10.1
  # annotation
  pull_to_refresh: ^2.0.0
  json_annotation: ^4.8.1
  # end Core
  #  infinite_scroll_pagination: ^4.0.0

  image_picker: ^1.0.7
  adaptive_action_sheet: ^2.0.3
  permission_handler: ^12.0.1
#  firebase_messaging: ^16.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  easy_localization: ^3.0.5
  api_request: ^1.0.0-pre-6
  # fluttertoast: ^8.2.4
  fluttertoast: ^8.2.12
  lottie: ^3.1.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.2.6
  # image_picker: ^0.8.6+1
  file_picker: ^10.3.2
  google_maps_flutter:
  flutter_polyline_points: ^3.0.1
  label_marker: ^1.0.1
  font_awesome_flutter: ^10.7.0
  location: ^8.0.1
  geocoding: ^4.0.0

  # location: ^5.0.3
  # google_maps_flutter: ^2.2.5
  # flutter_svg: any
  pin_code_text_field: ^1.8.0
  animate_do: ^4.2.0
  #======================================
  fl_chart: ^1.0.0
  path_provider:
  open_filex: ^4.6.0
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  timer_builder: ^2.0.0
  month_year_picker:
  extended_nested_scroll_view: ^6.2.1
  hexcolor: ^3.0.1
  flutter_otp_text_field: ^1.1.2+1
  flutter_datetime_picker_plus: ^2.2.0
  dotted_border: ^3.1.0
  pin_code_fields: ^8.0.1
  flexible_scrollbar: ^0.1.3
#  intl_utils: ^2.8.8
  marquee_widget: ^1.2.0
  ####### Dev Dependencies #########

  auto_route: ^10.1.2

dev_dependencies:
  #  ============================ Start dev Core Package ========
  auto_route_generator:
#  very_good_analysis: ^8.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_iconly:
  retrofit_generator: 9.7.0

  build_runner:
  injectable_generator: ^2.4.1
  # Asset generator
  flutter_gen_runner:
  # Freezed Code Generation
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  json_serializable: ^6.7.1


  ####### Dependencies Overrides #########
dependency_overrides:
#  intl: ^0.19.0
  meta: ^1.12.0



  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  generate: true
  uses-material-design: true

  assets:
#    - .env.dev
    - assets/translations/
    - .env.prod
    - assets/images/core/logos/
    - assets/images/core/png/
    - assets/images/core/animation/
    - assets/images/core/svg/
    - assets/images/demo/png/
    - assets/images/demo/svg/


  #    - assets/fonts/arabic/
  #    - assets/fonts/english/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  output: lib/core/presentation/util/style/images
  line_length: 80
  integrations:
    flutter_svg: true
    #    rive: true
    lottie: true

  ####### Assets #########
  assets:
    enabled: true
    outputs:
      class_name: AppImages
      package_parameter_enabled: false
      style: dot-delimiter
  ####### Fonts #########
  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  #  ============================ End dev Core Package ========